# exec-once = qs -c noctalia-shell
exec-once = waybar -c /home/mikku/.config/waybar/config-niri.jsonc -s /home/mikku/.config/waybar/css/style-niri.css
exec-once = dunst
exec-once = swayosd-server
exec-once = walker --gapplication-service
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# # Slow app launch fix -- set systemd vars
# exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
# exec-once = dbus-update-activation-environment --systemd --all

# Extra autostart processes
exec-once = xembedsniproxy
exec-once = faugus-launcher --hide
exec-once = [workspace 6] discord
exec-once = [workspace 5 silent] steam -silent

#Force workspaces onto certain monitors
workspace = 1,monitor:DP-2
workspace = 2,monitor:DP-2
workspace = 3,monitor:DP-2
workspace = 4,monitor:DP-2
workspace = 5,monitor:DP-2
workspace = 6,monitor:DP-3
workspace = 7,monitor:DP-3
workspace = 8,monitor:DP-3
workspace = 9,monitor:DP-3
workspace = 0,monitor:DP-3

