# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

windowrule {
  name = windowrule-1
  float = on
  fullscreen = on
  match:title = ^(World of Warcraft)$
}

# make sure battle.net does not launch fullscreen and is tiled
windowrule {
  name = windowrule-2
  tile = on
  size = 1920 1080
  match:title = ^(Battle.net)$
}



# Include overrides setting
source = ~/.config/hypr/conf-overrides.conf
